included:
  - Sources
  - Tests

disabled_rules:
  - block_based_kvo
  - class_delegate_protocol
  - colon
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - nesting
  - notification_center_detachment
  - redundant_string_enum_value
  - todo
  - trailing_comma
  - type_body_length
  - opening_brace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_string
  - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - first_where
  - generic_type_name
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - no_extension_access_modifier
  - override_in_extension
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

line_length:
  warning: 90
  error: 120
  ignores_urls: true

generic_type_name:
  min_length: 3

attributes:
  always_on_line_above:
    - "@usableFromInline"

custom_rules:
  no_foundation_dependency:
    included: Sources/OpenCombine/
    name: "No Foundation Dependency"
    regex: "^import.*Foundation.*$"
    message: "We don't want to depend on Foundation"
    severity: error

  no_dispatch_dependency:
    included: Sources/OpenCombine/
    name: "No Dispatch Dependency"
    regex: "^import.*Dispatch.*$"
    message: "We don't want to depend on Dispatch"
    severity: error

  inheritance_colon:
    name: "Inheritance Colon"
    regex: '\s[A-Z_]\w*(<[\w\s:\.,]+>)?(?: +:\s*|:(?:\s{0}|\s{2,}))([\[|\(]*\S)'
    message: "Colons should be next to the identifier of the inheriting type"
    severity: warning
    match_kinds:
      - identifier
      - typeidentifier

  dictionary_type_colon:
    name: "Dictionary Type Colon"
    regex: '\[\w+(?:(?:\s{0}|\s{2,}):| :(?:\s{0}|\s{2,})\w)'
    message: "Colon should be surrounded by a single whitespace in a dictionary literal"
    severity: warning
    match_kinds:
      - typeidentifier
