name: Compatibility tests 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9:00 AM

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests against Apple's Combine
        run: make test-compatibility
        